allowBuilds:
  core-js: set this to true or false
  es5-ext: set this to true or false
minimumReleaseAgeExclude:
  - '@tiptap/core@3.26.1'
  - '@tiptap/extension-blockquote@3.26.1'
  - '@tiptap/extension-bold@3.26.1'
  - '@tiptap/extension-bubble-menu@3.26.1'
  - '@tiptap/extension-bullet-list@3.26.1'
  - '@tiptap/extension-code-block-lowlight@3.26.1'
  - '@tiptap/extension-code-block@3.26.1'
  - '@tiptap/extension-code@3.26.1'
  - '@tiptap/extension-document@3.26.1'
  - '@tiptap/extension-dropcursor@3.26.1'
  - '@tiptap/extension-floating-menu@3.26.1'
  - '@tiptap/extension-gapcursor@3.26.1'
  - '@tiptap/extension-hard-break@3.26.1'
  - '@tiptap/extension-heading@3.26.1'
  - '@tiptap/extension-horizontal-rule@3.26.1'
  - '@tiptap/extension-image@3.26.1'
  - '@tiptap/extension-italic@3.26.1'
  - '@tiptap/extension-link@3.26.1'
  - '@tiptap/extension-list-item@3.26.1'
  - '@tiptap/extension-list-keymap@3.26.1'
  - '@tiptap/extension-list@3.26.1'
  - '@tiptap/extension-ordered-list@3.26.1'
  - '@tiptap/extension-paragraph@3.26.1'
  - '@tiptap/extension-strike@3.26.1'
  - '@tiptap/extension-text@3.26.1'
  - '@tiptap/extension-underline@3.26.1'
  - '@tiptap/extensions@3.26.1'
  - '@tiptap/pm@3.26.1'
  - '@tiptap/starter-kit@3.26.1'
  - '@tiptap/vue-3@3.26.1'
